#Stage 1: Build
FROM node:18-slim As builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY ..
#Stage 2: Production
FROM node:18-slim
#Non root user
RUN groupadd -r appuser && useradd -r appuser
WORKDIR /app
COPY --from=builder /app .
RUN chown -R appuser:appuser /app
USER appuser
EXPOSE 3000
CMD ["node", "index.js"]