apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: bW9uZ291c2Vy
  password: c2VjcmV0cGFzcw==
  uri: bW9uZ29kYjovL21vbmdvdXNlcjpzZWNyZXRwYXNzQG1vbmdvLXNlcnZpY2U6MjcwMTcvc2hvcGluZ2thcm8=
